### ISSUE TITLE
jul-26-midweek-Said

### ISSUE THREAD

**Issue by saidzaid** [UBCEnvision/CHBE241#20]
## Said's Work. What I've done:
 *Please write down a 2 -3  line summary of your work this week*

- Completed module 6
- This week I've been working on edits mostly, I finished most of all the suggestions from last week.
- Change steam tables drastically
- Change mixer to basic unit ops
- Added a lot to process economics

## Things I want you to know: 
*Please include things that you want people to know about your work*

- Victor had some good suggestions for moving stuff around.
- Having a bit of trouble coming up with a VLE example, any suggestions

## _Said_'s comments:

- I think it would be a good idea if everyone switched a module and did edits. For example, I switch to module 2 and make edits rather than just comments.
- We need to edit our images so that they contain the license.

**Comment by Corneliuscob** [comment]
in general it looks really good. 

- 4.1 has bolded learning objectives but the rest dont have highlighted terms. I think you can avoid using highlighted terms in the  L.O in general since they should be the clearest/first theing they read
- the Eos looks realyl good. I like the python implementation.
- the steam tables looks really realyl good I want t impement taht as well
 - is it possible to highlight the cells that are of interest?
- hess's law.  you worked on state functions nad path functions 
 - I covred that in module 5.  you can redirect them or keep wha you have 
 - the naming is inconsistent. 
  - path independent then you call it a state function
 - it mentions that the rate of reaction is slow, therefore the heat of reaction cannot be easured?  I dont realyl understand 

- latent heats. Should probabaly throw a new issue about this,  I think thsi should go in module 5 

- heat of formations is really well done ! 
 - Shuld probs throwan issue and put heat of mixing  in this module !

**Comment by saidzaid** [comment]
Aren't state functions path independent?
