### ISSUE TITLE
DOF page sample problem

### ISSUE THREAD

**Issue by jverrett** [UBCEnvision/CHBE241#8]
BFD should be added for the solution and the species (eg air and water perhaps) should be more specific in the question or written as an assumption in the solution. 

Interesting way to look at this may be to have it analyzed with N2 and O2 as species vs using just air.

Can also leave this update for later in case problems should be more closely linked to module examples.

**Comment by saidzaid** [comment]
There is a block flow diagram in the question, I am not sure why some of the images are not showing up for you.

The BFD shows the break down pretty well for the air. I believe t adds a bit of complexity for the students since questions may be asked like this. I will check with siang on why the images are not showing up in the sygzy server.

**Comment by saidzaid** [comment]
Hi Dr. Verrett, have you taken a look at the question since the edit? Can we close the issure for now or should we still change it some more?

**Comment by jverrett** [comment]
DOF page still has no image, which is fine.

However the Block Flow Diagram (BFD) section says they show Process Flow Diagrams (PFD) rather than BFDs. What is illustrated is BFDs so this should be changed. 

No need to change the question, and we can close this issue once the BFD section is updated

**Comment by saidzaid** [comment]
I have changed the PFD to a BFD.
